services:
  - type: web
    name: todo-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**/*.{js,jsx,ts,tsx}
        - server/**/*.{js,ts}
        - package.json
        - package-lock.json
        - vite.config.ts
    healthCheckPath: /
    healthCheckTimeout: 5s
    disk:
      name: todo-app-data
      mountPath: /data
      sizeGB: 1

